using Adohope.Modules.ManifestDb.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace Adohope.Modules.VoiceNotes.Models
{
    public class Recording
    {
        // This is the row id in the ZRECORDING table
        public long ID { get; set; }
        // This is an ID generated by the iOS system and is store in separate table.
        public long RecordingID { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan Duration { get; set; }
        public string Label { get; set; }
        public string Path { get; set; } //(/var/mobile/Media/Recordings/20190131 084239.m4a)
        public string RelativePath { get => Path.Replace("/var/mobile/", string.Empty); }
        public MBFile MBFile { get; set; }
    }
}
